### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by setzsc** [rupava/Spotify-Stream-Logger#1]
Plays only show on playlists & not albums
![image](https://github.com/user-attachments/assets/ea9a0271-55cd-4f2e-b353-d9eba017b2c9)
![image](https://github.com/user-attachments/assets/e8c91c0e-d785-441d-a825-77f9bad63b40)

**Comment by rupava** [comment]
I'll check on it, can you please provide me with the links to the album and the playlist so that I can replicate the issue?

**Comment by setzsc** [comment]
It happens on every album & only works on my playlists
